import Foundation

/// Renders an outage + post-mortem as a Markdown report suitable for pasting
/// into an ISP support ticket or a Slack message.
enum MarkdownReport {
    static func render(outage: OutageEvent, postMortem: OutagePostMortem?) -> String {
        var out: [String] = []

        let kind = outage.type == .connectivity ? "Connectivity outage" : "Partial outage"
        out.append("# \(kind)")
        out.append("")

        let started = outage.startTime.formatted(date: .complete, time: .standard)
        out.append("- **Started:** \(started)")
        if let endTime = outage.endTime {
            out.append("- **Ended:** \(endTime.formatted(date: .complete, time: .standard))")
        } else {
            out.append("- **Ended:** _ongoing_")
        }
        out.append("- **Duration:** \(outage.effectiveDuration.humanDuration)")
        out.append("- **Packet loss at start:** \(String(format: "%.1f%%", outage.startPacketLoss))")
        out.append("- **DNS at start:** \(outage.startDNSFailure ? "failure" : "OK")")
        out.append("- **Outage id:** `\(outage.id)`")
        out.append("")

        if let pm = postMortem {
            if let eth = pm.ethernet {
                out.append("## \(eth.displayName) at the moment of failure")
                out.append("")
                out.append("| | |")
                out.append("|---|---|")
                out.append("| Interface | `\(eth.interface)` |")
                if let port = eth.hardwarePort { out.append("| Hardware port | \(port) |") }
                out.append("| Link | \(eth.linkActive ? "active" : "down") |")
                if let media = eth.media { out.append("| Media | `\(media)` |") }
                if let mac = eth.macAddress { out.append("| MAC | `\(mac)` |") }
                if let ip = eth.ipAddress { out.append("| IP | `\(ip)` |") }
                if let mtu = eth.mtu { out.append("| MTU | \(mtu) |") }
                out.append("")
            } else if let wifi = pm.wifi {
                out.append("## Wi-Fi at the moment of failure")
                out.append("")
                out.append("| | |")
                out.append("|---|---|")
                out.append("| Interface | `\(wifi.interface)` |")
                out.append("| Network | \(wifi.ssid ?? "_unavailable_") |")
                out.append("| BSSID | `\(wifi.bssid ?? "unavailable")` |")
                out.append("| Signal | \(wifi.rssiDBm) dBm |")
                out.append("| Noise | \(wifi.noiseDBm) dBm |")
                if let ch = wifi.channel {
                    out.append("| Channel | \(ch) |")
                }
                if wifi.transmitRateMbps > 0 {
                    out.append("| TX rate | \(Int(wifi.transmitRateMbps)) Mbps |")
                }
                out.append("")
            }

            if let gw = pm.gatewayIP {
                out.append("## Routing")
                out.append("")
                out.append("- **Default gateway:** `\(gw)`")
                out.append("")
            }

            if let hops = pm.traceroute, !hops.isEmpty {
                out.append("## Traceroute")
                out.append("")
                out.append("```")
                for hop in hops {
                    let ip = hop.ip ?? "*"
                    let rtt = hop.rttMs.map { String(format: "%6.2f ms", $0) } ?? "timeout"
                    out.append(String(format: "%2d  %-16s  %@", hop.index, ip, rtt))
                }
                out.append("```")
                out.append("")
            }

            if !pm.recentSystemEvents.isEmpty {
                out.append("## Nearby system events")
                out.append("")
                for ev in pm.recentSystemEvents {
                    let t = ev.timestamp.formatted(date: .omitted, time: .standard)
                    out.append("- \(t) — \(ev.kind.label)")
                }
                out.append("")
            }
        } else {
            out.append("_(No post-mortem captured for this outage.)_")
            out.append("")
        }

        out.append("---")
        out.append("_Generated by Netmon_")
        return out.joined(separator: "\n")
    }
}
